/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fonted.empleado;

/**
 *
 * @author Artist
 */
public class vistaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaCliente
     */
    public vistaCliente() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPaneAdministrar = new javax.swing.JTabbedPane();
        jPanelCrear = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombreClienteCrear = new javax.swing.JLabel();
        jLabelNitClienteCrear = new javax.swing.JLabel();
        jLabelTelefonoClienteCrear = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNombreCrear = new javax.swing.JTextField();
        jTextFieldNitCrear = new javax.swing.JTextField();
        jTextFieldTelefonoCrear = new javax.swing.JTextField();
        jTextFieldCreditoCrear = new javax.swing.JTextField();
        jTextFieldDpiCrear = new javax.swing.JTextField();
        jTextFieldCorreoCrear = new javax.swing.JTextField();
        jTextFieldDireccionCrear = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jComboBoxNitLetraCrear = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabelObligatorioCrear = new javax.swing.JLabel();
        jLabelObligatorioCrear1 = new javax.swing.JLabel();
        jLabelObligatorioCrear2 = new javax.swing.JLabel();
        jPanelModificarEliminar = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabelNombreModificarEliminar = new javax.swing.JLabel();
        jLabelNitModificarEliminar = new javax.swing.JLabel();
        jLabelTelefonoModificarEliminar = new javax.swing.JLabel();
        jLabelCreditoModificarEliminar = new javax.swing.JLabel();
        jLabelDpiModificarEliminar = new javax.swing.JLabel();
        jLabelCorreoModificarEliminar = new javax.swing.JLabel();
        jLabelDireccionModificarEliminar = new javax.swing.JLabel();
        jTextFieldNombreModificarEliminar = new javax.swing.JTextField();
        jTextFieldNitModificarEliminar = new javax.swing.JTextField();
        jTextFieldTelefonoModificarEliminar = new javax.swing.JTextField();
        jTextFieldCreditoModificarEliminar = new javax.swing.JTextField();
        jTextFieldDpiModificarEliminar = new javax.swing.JTextField();
        jTextFieldCorreoModificarEliminar = new javax.swing.JTextField();
        jTextFieldDireccionModificarEliminar = new javax.swing.JTextField();
        jLabelObligatorioModificarEliminar = new javax.swing.JLabel();
        jLabelObligatorioModificarEliminar2 = new javax.swing.JLabel();
        jLabelObligatorioModificarEliminar3 = new javax.swing.JLabel();
        jButtonRealizarAccion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonModificarAccion = new javax.swing.JRadioButton();
        jRadioButtonEliminarAccion = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();

        setBorder(null);
        setMinimumSize(new java.awt.Dimension(0, 0));

        jLabelNombreClienteCrear.setText("Nombre:");

        jLabelNitClienteCrear.setText("NIT:");

        jLabelTelefonoClienteCrear.setText("Telefono:");

        jLabel4.setText("Credito Compra:");

        jLabel5.setText("DPI:");

        jLabel6.setText("Correo Electronico:");

        jLabel7.setText("Direccion:");

        jTextFieldNombreCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCrearActionPerformed(evt);
            }
        });

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jLabel1.setText("-");

        jLabelObligatorioCrear.setForeground(new java.awt.Color(255, 0, 0));
        jLabelObligatorioCrear.setText("jLabel2");

        jLabelObligatorioCrear1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelObligatorioCrear1.setText("jLabel2");

        jLabelObligatorioCrear2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelObligatorioCrear2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabelNombreClienteCrear)
                            .addComponent(jLabelNitClienteCrear)
                            .addComponent(jLabelTelefonoClienteCrear)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldTelefonoCrear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCreditoCrear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDpiCrear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCorreoCrear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDireccionCrear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxNitLetraCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNitCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                            .addComponent(jTextFieldNombreCrear))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelObligatorioCrear)
                    .addComponent(jLabelObligatorioCrear1)
                    .addComponent(jLabelObligatorioCrear2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldNombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreClienteCrear)
                    .addComponent(jLabelObligatorioCrear))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelNitClienteCrear)
                    .addComponent(jTextFieldNitCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNitLetraCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelObligatorioCrear1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelTelefonoClienteCrear)
                    .addComponent(jTextFieldTelefonoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObligatorioCrear2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldCreditoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDpiCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCorreoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDireccionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCrearLayout = new javax.swing.GroupLayout(jPanelCrear);
        jPanelCrear.setLayout(jPanelCrearLayout);
        jPanelCrearLayout.setHorizontalGroup(
            jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanelCrearLayout.setVerticalGroup(
            jPanelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jTabbedPaneAdministrar.addTab("Crear", jPanelCrear);

        jLabelNombreModificarEliminar.setText("Nombre:");

        jLabelNitModificarEliminar.setText("NIT:");

        jLabelTelefonoModificarEliminar.setText("Telefono:");

        jLabelCreditoModificarEliminar.setText("Credito Compra:");

        jLabelDpiModificarEliminar.setText("DPI:");

        jLabelCorreoModificarEliminar.setText("Correo Electronico:");

        jLabelDireccionModificarEliminar.setText("Direccion:");

        jTextFieldNombreModificarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreModificarEliminarActionPerformed(evt);
            }
        });

        jLabelObligatorioModificarEliminar.setForeground(new java.awt.Color(255, 0, 0));
        jLabelObligatorioModificarEliminar.setText("jLabel2");

        jLabelObligatorioModificarEliminar2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelObligatorioModificarEliminar2.setText("jLabel2");

        jLabelObligatorioModificarEliminar3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelObligatorioModificarEliminar3.setText("jLabel2");

        jButtonRealizarAccion.setText("Realizar Accion");
        jButtonRealizarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarAccionActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        buttonGroup1.add(jRadioButtonModificarAccion);
        jRadioButtonModificarAccion.setText("Modificar");

        buttonGroup1.add(jRadioButtonEliminarAccion);
        jRadioButtonEliminarAccion.setText("Eliminar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonModificarAccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonEliminarAccion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonModificarAccion)
                    .addComponent(jRadioButtonEliminarAccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCreditoModificarEliminar)
                            .addComponent(jLabelNombreModificarEliminar)
                            .addComponent(jLabelNitModificarEliminar)
                            .addComponent(jLabelTelefonoModificarEliminar)
                            .addComponent(jLabelDpiModificarEliminar)
                            .addComponent(jLabelCorreoModificarEliminar)
                            .addComponent(jLabelDireccionModificarEliminar))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldTelefonoModificarEliminar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCreditoModificarEliminar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDpiModificarEliminar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCorreoModificarEliminar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDireccionModificarEliminar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombreModificarEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextFieldNitModificarEliminar)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRealizarAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelObligatorioModificarEliminar)
                    .addComponent(jLabelObligatorioModificarEliminar2)
                    .addComponent(jLabelObligatorioModificarEliminar3))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldNombreModificarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreModificarEliminar)
                    .addComponent(jLabelObligatorioModificarEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelNitModificarEliminar)
                    .addComponent(jTextFieldNitModificarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObligatorioModificarEliminar2))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelTelefonoModificarEliminar)
                    .addComponent(jTextFieldTelefonoModificarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObligatorioModificarEliminar3))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldCreditoModificarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCreditoModificarEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDpiModificarEliminar)
                    .addComponent(jTextFieldDpiModificarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCorreoModificarEliminar)
                    .addComponent(jTextFieldCorreoModificarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccionModificarEliminar)
                    .addComponent(jTextFieldDireccionModificarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRealizarAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelModificarEliminarLayout = new javax.swing.GroupLayout(jPanelModificarEliminar);
        jPanelModificarEliminar.setLayout(jPanelModificarEliminarLayout);
        jPanelModificarEliminarLayout.setHorizontalGroup(
            jPanelModificarEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificarEliminarLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanelModificarEliminarLayout.setVerticalGroup(
            jPanelModificarEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPaneAdministrar.addTab("Modificar / Eliminar", jPanelModificarEliminar);

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jTabbedPaneAdministrar)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneAdministrar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCrearActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed

    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonRealizarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarAccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRealizarAccionActionPerformed

    private void jTextFieldNombreModificarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreModificarEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreModificarEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton jButtonCrear;
    public javax.swing.JButton jButtonRealizarAccion;
    public javax.swing.JComboBox<String> jComboBoxNitLetraCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCorreoModificarEliminar;
    private javax.swing.JLabel jLabelCreditoModificarEliminar;
    private javax.swing.JLabel jLabelDireccionModificarEliminar;
    private javax.swing.JLabel jLabelDpiModificarEliminar;
    public javax.swing.JLabel jLabelNitClienteCrear;
    public javax.swing.JLabel jLabelNitModificarEliminar;
    public javax.swing.JLabel jLabelNombreClienteCrear;
    public javax.swing.JLabel jLabelNombreModificarEliminar;
    public javax.swing.JLabel jLabelObligatorioCrear;
    public javax.swing.JLabel jLabelObligatorioCrear1;
    public javax.swing.JLabel jLabelObligatorioCrear2;
    public javax.swing.JLabel jLabelObligatorioModificarEliminar;
    public javax.swing.JLabel jLabelObligatorioModificarEliminar2;
    public javax.swing.JLabel jLabelObligatorioModificarEliminar3;
    public javax.swing.JLabel jLabelTelefonoClienteCrear;
    public javax.swing.JLabel jLabelTelefonoModificarEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCrear;
    private javax.swing.JPanel jPanelModificarEliminar;
    public javax.swing.JRadioButton jRadioButtonEliminarAccion;
    public javax.swing.JRadioButton jRadioButtonModificarAccion;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPaneAdministrar;
    public javax.swing.JTable jTableCliente;
    public javax.swing.JTextField jTextFieldCorreoCrear;
    public javax.swing.JTextField jTextFieldCorreoModificarEliminar;
    public javax.swing.JTextField jTextFieldCreditoCrear;
    public javax.swing.JTextField jTextFieldCreditoModificarEliminar;
    public javax.swing.JTextField jTextFieldDireccionCrear;
    public javax.swing.JTextField jTextFieldDireccionModificarEliminar;
    public javax.swing.JTextField jTextFieldDpiCrear;
    public javax.swing.JTextField jTextFieldDpiModificarEliminar;
    public javax.swing.JTextField jTextFieldNitCrear;
    public javax.swing.JTextField jTextFieldNitModificarEliminar;
    public javax.swing.JTextField jTextFieldNombreCrear;
    public javax.swing.JTextField jTextFieldNombreModificarEliminar;
    public javax.swing.JTextField jTextFieldTelefonoCrear;
    public javax.swing.JTextField jTextFieldTelefonoModificarEliminar;
    // End of variables declaration//GEN-END:variables
}
